shortcuts: https://medium.com/@tuewithmorris/google-colab-notebooks-keyboard-shortcuts-aa6a008fb91b

# Brampton Business Dataset

The Brampton Business Directory is an employer census of all brick and mortar businesses operating within the city and features over 8,900 records.  The directory contains information such as company name, business description, address, website and North American Industry Classification Code, the year the business was established in Brampton and the year the business was established as a business._

*http://geohub.brampton.ca/datasets/brampton-business-directory*

## ***Analysis***

Using this dataset we were able to determine:

1) top 10 employers in Brampton: (accounts for 15% of total employment in Brampton) 22,998 employees (of 150,413 employees in Brampton)

2) top 1% of employers in Brampton (97 companies), generate 35.5% of all employment in Brampton

## ***Initial Configurations***

In [ ]:
# Import common directories
import os, shutil, re
import pandas as pd
import numpy as np
import requests
import io
import seaborn as sns
%load_ext google.colab.data_table

/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm

In [ ]:
# Load Google Drive (Run once)
!pip install -U -q PyDrive
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials
# Authenticate and create the PyDrive client.
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

In [ ]:
# Get link from Google Drive and update link below
link = 'https://drive.google.com/open?id=1G61RKq_VNlhla1iEUahDtdnfcI6FcoNS' # The shareable link
fluff, id = link.split('=')
print (id) # Verify that you have everything after '='

1G61RKq_VNlhla1iEUahDtdnfcI6FcoNS

In [ ]:
downloaded = drive.CreateFile({'id': id}) 
downloaded.GetContentFile('Brampton_Business_Directory.csv')

In [ ]:
url="https://opendata.arcgis.com/datasets/3cd59a895f404612b57e4c84fc8931be_0.csv?outSR=%7B%22latestWkid%22%3A3857%2C%22wkid%22%3A102100%7D"
s=requests.get(url).content
BB_df=pd.read_csv(io.StringIO(s.decode('utf-8')))
# BB_df = pd.read_csv('Brampton_Business_Directory.csv')

In [ ]:
# !ls "/content/drive/My Drive"

## *Data Exploration*

In [ ]:
BB_df['UPDATE_DATE'].unique()

array(['2019/06/14 18:27:10+00', '2019/07/02 21:37:58+00',
       '2019/08/01 16:39:32+00', ..., '2020/03/26 00:27:56+00',
       '2020/04/21 22:28:14+00', '2020/04/21 23:51:15+00'], dtype=object)

In [ ]:
BB_df.columns

Index(['X', 'Y', 'OBJECTID', 'COMPANY_NAME', 'OPERATIONAL', 'STREET_NUM',
       'STREET_NAME', 'STREET_TYPE', 'STREET_DIRECTION', 'UNIT',
       'BUSINESS_FULL_ADDRESS', 'CITY', 'PROVINCE', 'POSTAL_CODE', 'PHONE',
       'FAX', 'WEBURL', 'DATE_EST_IN_CITY', 'STARTED_IN_CITY',
       'HEAD_OFFICE_LOCATION', 'TOTAL_EMPLOYEE', 'SHIFTS', 'SHIFT_NUMBER',
       'GFA_SQUARE_FEET', 'GFA_SQUARE_METER', 'NAIC_2', 'NAIC_3', 'NAIC_4',
       'NAIC_6', 'PRODUCT_DESC', 'EXPORTS', 'EXPORT_PERCENTAGE',
       'EXPORT_COUNTRY1', 'EXPORT_COUNTRY2', 'EXPORT_COUNTRY3', 'UPDATE_DATE',
       'UPDATED_BY', 'NAICS_DETAIL', 'CREATED_BY', 'CREATE_DATE', 'FACEBOOK',
       'TWITTER', 'LINKEDIN', 'YOUTUBE', 'INSTAGRAM', 'GLOBALID'],
      dtype='object')

In [ ]:
BB_df.head()

              X             Y  ...  INSTAGRAM                                GLOBALID
0 -8.879769e+06  5.421624e+06  ...        NaN  {2069426F-5FB3-487C-BE76-2938C13C62F1}
1 -8.875687e+06  5.413618e+06  ...        NaN  {91B56BDD-0C8C-494F-B229-53067D34BBE0}
2 -8.873948e+06  5.428276e+06  ...        NaN  {23A97157-EB06-4C1C-9DB8-6C7A94FCA35B}
3 -8.869585e+06  5.421456e+06  ...        NaN  {74FDEAF8-F173-48AF-B38E-B5B6406BAFF2}
4 -8.871856e+06  5.426546e+06  ...        NaN  {79C1C11E-4411-47D3-A4CD-CA724B62637A}

[5 rows x 46 columns]

In [ ]:
BB_df.columns

Index(['X', 'Y', 'OBJECTID', 'COMPANY_NAME', 'OPERATIONAL', 'STREET_NUM',
       'STREET_NAME', 'STREET_TYPE', 'STREET_DIRECTION', 'UNIT',
       'BUSINESS_FULL_ADDRESS', 'CITY', 'PROVINCE', 'POSTAL_CODE', 'PHONE',
       'FAX', 'WEBURL', 'DATE_EST_IN_CITY', 'STARTED_IN_CITY',
       'HEAD_OFFICE_LOCATION', 'TOTAL_EMPLOYEE', 'SHIFTS', 'SHIFT_NUMBER',
       'GFA_SQUARE_FEET', 'GFA_SQUARE_METER', 'NAIC_2', 'NAIC_3', 'NAIC_4',
       'NAIC_6', 'PRODUCT_DESC', 'EXPORTS', 'EXPORT_PERCENTAGE',
       'EXPORT_COUNTRY1', 'EXPORT_COUNTRY2', 'EXPORT_COUNTRY3', 'UPDATE_DATE',
       'UPDATED_BY', 'NAICS_DETAIL', 'CREATED_BY', 'CREATE_DATE', 'FACEBOOK',
       'TWITTER', 'LINKEDIN', 'YOUTUBE', 'INSTAGRAM', 'GLOBALID'],
      dtype='object')

In [ ]:
BB_df.describe()

                  X             Y  ...  EXPORT_PERCENTAGE   NAICS_DETAIL
count  9.758000e+03  9.758000e+03  ...         392.000000    9736.000000
mean  -8.876345e+06  5.420669e+06  ...          33.456633  553320.704601
std    4.639757e+03  5.279228e+03  ...          31.041811  158697.525315
min   -8.888962e+06  5.404637e+06  ...           0.000000  111190.000000
25%   -8.879323e+06  5.417082e+06  ...           5.000000  445291.000000
50%   -8.876075e+06  5.419934e+06  ...          20.000000  541212.000000
75%   -8.872929e+06  5.424343e+06  ...          50.000000  713940.000000
max   -8.865101e+06  5.439549e+06  ...         100.000000  999999.000000

[8 rows x 9 columns]

In [ ]:
len(np.unique(BB_df['COMPANY_NAME']))

8554

In [ ]:
len(BB_df['COMPANY_NAME'].unique().tolist())

8554

In [ ]:
BB_df.groupby('COMPANY_NAME')['COMPANY_NAME'].count().sort_values(ascending=False)

COMPANY_NAME
TIM HORTONS                      63
SUBWAY                           44
HASTY MARKET                     35
PETRO CANADA                     22
RBC ROYAL BANK                   22
                                 ..
OBAAPA IMPEX LTD.                 1
OBRIEN AND ASSOCIATES             1
OBRIEN RICHARD                    1
OBSESSION                         1
1 2 3 COMPUTER WAREHOUSE INC.     1
Name: COMPANY_NAME, Length: 8554, dtype: int64

In [ ]:
Emp_sum = BB_df['TOTAL_EMPLOYEE'].sum()

In [ ]:
Emp_sum

153512.0

In [ ]:
BB_group = BB_df.groupby('COMPANY_NAME')['TOTAL_EMPLOYEE'].sum().sort_values(ascending=False)

In [ ]:
BB_group

COMPANY_NAME
ROGERS COMMUNICATIONS                               5200.0
FCA CANADA INC.                                     3068.0
MAPLE LODGE FARMS                                   3000.0
AMAZON                                              2650.0
LOBLAW COMPANIES LTD.                               2500.0
                                                     ...
THE JACK ROLLERS                                       0.0
THE KATHI ROLL EXPRESS                                 0.0
KARAHI STOP                                            0.0
RAMANJEET TUNG PROFESSIONAL CORPORATION, CPA, CA       0.0
MEXICO IN TOWN                                         0.0
Name: TOTAL_EMPLOYEE, Length: 8554, dtype: float64

In [ ]:
# Change: groupby state_office and divide by sum
BB_pcts = BB_group.groupby(level=0).apply(lambda x:
                                                 100 * (x / Emp_sum))

In [ ]:
BB_pcts

COMPANY_NAME
ROGERS COMMUNICATIONS                               3.387357
FCA CANADA INC.                                     1.998541
MAPLE LODGE FARMS                                   1.954245
AMAZON                                              1.726249
LOBLAW COMPANIES LTD.                               1.628537
                                                      ...
THE JACK ROLLERS                                    0.000000
THE KATHI ROLL EXPRESS                              0.000000
KARAHI STOP                                         0.000000
RAMANJEET TUNG PROFESSIONAL CORPORATION, CPA, CA    0.000000
MEXICO IN TOWN                                      0.000000
Name: TOTAL_EMPLOYEE, Length: 8554, dtype: float64

In [ ]:
# BB_df.loc[BB_df.TOTAL_EMPLOYEE.idxmax()]

In [ ]:
BB_df.sort_values("TOTAL_EMPLOYEE", axis = 0, ascending = False, 
                 inplace = True, na_position ='last')

In [ ]:
BB_df.replace(np.nan, '', regex=True)
BB_df.head()

                 X  ...                                GLOBALID
6439 -8.874074e+06  ...  {DA312F43-96DD-4853-B25D-EFE46BED3DAB}
8654 -8.873636e+06  ...  {BD9AB5AC-1D5D-4848-9F70-8F5FE4C9B8E7}
7823 -8.883809e+06  ...  {9FB7B5FC-A999-4768-8B7C-5A15060C4C4B}
8095 -8.879829e+06  ...  {F12E1E0C-13DE-4ADD-88FE-9D9C7464F796}
4793 -8.876530e+06  ...  {CEE49EB8-1CA8-44E3-B384-48E7C9F07871}

[5 rows x 46 columns]

In [ ]:
BB_df.head(10)

                 X  ...                                GLOBALID
6439 -8.874074e+06  ...  {DA312F43-96DD-4853-B25D-EFE46BED3DAB}
8654 -8.873636e+06  ...  {BD9AB5AC-1D5D-4848-9F70-8F5FE4C9B8E7}
7823 -8.883809e+06  ...  {9FB7B5FC-A999-4768-8B7C-5A15060C4C4B}
8095 -8.879829e+06  ...  {F12E1E0C-13DE-4ADD-88FE-9D9C7464F796}
4793 -8.876530e+06  ...  {CEE49EB8-1CA8-44E3-B384-48E7C9F07871}
9074 -8.882855e+06  ...  {13CA1B1D-9837-404E-ADB5-76622A69DD8F}
9075 -8.882197e+06  ...  {2AEAFC6A-4503-4B9D-BEEF-29C6D11226AD}
8846 -8.869330e+06  ...  {C62976B7-F343-470C-B76E-FFB26A93050D}
8708 -8.869454e+06  ...  {AA5ED00C-237B-4477-AF27-40A41087F649}
9354 -8.872103e+06  ...  {F309EFC2-0ED2-40D0-8EF7-952CB7DBC81F}

[10 rows x 46 columns]

### Total Employee Analysis

In [ ]:
Emp_count = BB_df[['COMPANY_NAME', 'TOTAL_EMPLOYEE',  'NAIC_2', 'NAIC_3', 'NAIC_4','NAIC_6', 'PRODUCT_DESC']]

In [ ]:
Emp_count = Emp_count.sort_values("TOTAL_EMPLOYEE",axis=0,ascending=False,inplace=False,na_position='last')

In [ ]:
Emp_count.index = range(1,len(Emp_count)+1)

In [ ]:
Emp_count.describe()

       TOTAL_EMPLOYEE
count     9680.000000
mean        15.858678
std         91.181956
min          0.000000
25%          1.000000
50%          3.000000
75%          9.000000
max       5200.000000

#### Sum of Employeesin Top 10 companies by Employee size

In [ ]:
Emp_in_Top10 = Emp_count.head(10)['TOTAL_EMPLOYEE'].sum()

In [ ]:
Emp_in_Top10

22005.0

In [ ]:
Total_Employees = Emp_count['TOTAL_EMPLOYEE'].sum()

In [ ]:
Ratio1 = (Emp_in_Top10/Total_Employees)*100

In [ ]:
Ratio1

14.334384282661942

In [ ]:
Emp_count.count()[0]

9758

#### Sum of Employees in Top 1 % of Companies with highest # of Employees

In [ ]:
Emp_count.count()

COMPANY_NAME      9758
TOTAL_EMPLOYEE    9680
NAIC_2            9737
NAIC_3            9737
NAIC_4            9737
NAIC_6            9737
PRODUCT_DESC      9195
dtype: int64

In [ ]:
Onepcnt = 0.01 * (Emp_count.count()[0])
Onepcnt = int(round(Onepcnt))
Emp_in_Top1pcnt = Emp_count.head(Onepcnt)['TOTAL_EMPLOYEE'].sum()

In [ ]:
Ratio2 = (Emp_in_Top1pcnt/Total_Employees)*100

In [ ]:
Ratio2

35.13340976601177

In [ ]:
Emp_in_Top1pcnt

53934.0

In [ ]:
Total_Employees

153512.0

In [ ]:
Onepcnt

98

In [ ]:
Ratio2

35.13340976601177

In [ ]:
Emp_count.NAIC_2.value_counts()

Retail                                                1823
Other Services (except Public Administration)         1203
Accommodation and Food Services                       1154
Health Care and Social Assistance                     1123
Professional, Scientific and Technical Services        892
Manufacturing                                          801
Construction                                           429
Wholesale Trade                                        408
Administrative and Support, Waste Management and R     381
Finance and Insurance                                  351
Transportation and Warehousing                         348
Educational Services                                   285
Real Estate and Rental and Leasing                     247
Arts, Entertainment and Recreation                     151
Information and Cultural Industries                     80
Agriculture, Forestry, Fishing and Hunting              21
Public Administration                                   15
Utilities                                               14
Management of Companies and Enterprises                  8
Mining and Oil and Gas Extraction                        2
Unspecified                                              1
Name: NAIC_2, dtype: int64

#### Number of Employees in XYZ company

In [ ]:
Emp_count.head()

                                        COMPANY_NAME  ...                                       PRODUCT_DESC
1                              ROGERS COMMUNICATIONS  ...  WIRELESS, DIGITAL CABLE & HI-SPEED INTERNET PR...
2                                    FCA CANADA INC.  ...                          AUTOMOBILE ASSEMBLY PLANT
3                                  MAPLE LODGE FARMS  ...                                 POULTRY PROCESSING
4                              LOBLAW COMPANIES LTD.  ...            HEAD OFFICE OF FOOD AND BEVERAGE RETAIL
5  SHERIDAN COLLEGE INSTITUTE OF TECHNOLOGY AND A...  ...                                COLLEGE - EDUCATION

[5 rows x 7 columns]

In [ ]:
CompName = Emp_count['COMPANY_NAME']
Company1 = CompName.str.contains("ROGERS")
Emp_count[Company1]

               COMPANY_NAME  ...                                       PRODUCT_DESC
1     ROGERS COMMUNICATIONS  ...  WIRELESS, DIGITAL CABLE & HI-SPEED INTERNET PR...
1854            ROGERS PLUS  ...                            VIDEO SALES AND RENTALS
2162                 ROGERS  ...                            VIDEO SALES AND RENTALS
2729                 ROGERS  ...                         TELECOMMUNICATION SERVICES
2907        ROGERS WIRELESS  ...  WIRELESS SERVICE PROVIDER AND RETAIL FOR CELL ...
3047        ROGERS WIRELESS  ...                  CELLULAR TELEPHONES & ACCESSORIES
3393        ROGERS WIRELESS  ...                               CELL PHONES & PAGERS
4317           ROGERS VIDEO  ...  VIDEO SALES AND RENTALS, ACTIVATE CELL PHONES ...
7511                 ROGERS  ...                         TELECOMMUNICATIONS CARRIER
8044                 ROGERS  ...                         TELECOMMUNICATION PROVIDER
8268                 ROGERS  ...                        TELECOMMUNICATIONS PROVIDER
8478                 ROGERS  ...                         TELECOMMUNICATIONS CARRIER

[12 rows x 7 columns]

In [ ]:
BB_df[BB_df['COMPANY_NAME'] =='ROGERS VIDEO']

                 X  ...                                GLOBALID
5662 -8.881779e+06  ...  {07231E81-C571-4E92-BC6C-150F148441D2}

[1 rows x 46 columns]

In [ ]:
Company2 = CompName.str.contains("AMAZON")
Emp_count[Company2]

                COMPANY_NAME  ...                     PRODUCT_DESC
6                     AMAZON  ...  FULFILLMENT DISTRIBUTION CENTRE
7                     AMAZON  ...  FULFILLMENT DISTRIBUTION CENTRE
6900  AMAZON HARDWOOD CENTRE  ...                HARDWOOD RESELLER

[3 rows x 7 columns]

In [ ]:
BB_df[BB_df['COMPANY_NAME'] =='AMAZON']

                 X  ...                                GLOBALID
9074 -8.882855e+06  ...  {13CA1B1D-9837-404E-ADB5-76622A69DD8F}
9075 -8.882197e+06  ...  {2AEAFC6A-4503-4B9D-BEEF-29C6D11226AD}

[2 rows x 46 columns]

In [ ]:
Emp_count.loc[97:98]

            COMPANY_NAME  ...                         PRODUCT_DESC
97        AFRICAN SAFARI  ...  AFRICAN AND CARIBBEAN GORCERY STORE
98  RONA HOME AND GARDEN  ...              HOME IMPROVEMENT CENTRE

[2 rows x 7 columns]

In [ ]:
MyNeigh_df = BB_df.dropna(subset = ['POSTAL_CODE'])
MyNeighborhood = MyNeigh_df.POSTAL_CODE.str.contains('L7A')
MyNeigh_df[MyNeighborhood]

                 X  ...                                GLOBALID
6679 -8.883502e+06  ...  {180F3205-4342-47FA-8C75-EB7DD32D4767}
7161 -8.884331e+06  ...  {10ABB5DD-E903-44C6-8138-550FBB285EDC}
6145 -8.884967e+06  ...  {B73822B0-DBF3-4F39-A070-97286C919656}
7318 -8.884033e+06  ...  {3F8D02D9-0E82-47BE-A452-580CC22F784A}
9505 -8.884000e+06  ...  {13F12C8B-5A14-4CF2-8273-F0A03CFF648E}
...            ...  ...                                     ...
8273 -8.883260e+06  ...  {ECAAD427-C9B2-49CC-8A27-01A078F2F5EE}
8742 -8.883358e+06  ...  {EA503B7D-0824-476B-B092-D200AC3F7DD1}
8949 -8.883474e+06  ...  {D68215CA-A271-4EB3-9AFA-D5CB1D28BCCD}
9527 -8.882164e+06  ...  {B03C2710-BBFF-4D5F-A264-37B7FF6E4B58}
9648 -8.888778e+06  ...  {AD81D674-FE4E-4287-83F4-4083ED3CD9D6}

[696 rows x 46 columns]

In [ ]:
BB_df[BB_df['POSTAL_CODE']=='L6Z 4P7']

                 X  ...                                GLOBALID
6479 -8.885878e+06  ...  {DC6CAB3E-7874-4BE0-8AB7-ED8392ABFE46}
5259 -8.886004e+06  ...  {DE802BDF-C21F-40FE-83A6-F5136669F14B}
6601 -8.886076e+06  ...  {4FEDC491-69B3-4207-9899-C0FDECB8B36D}
8710 -8.879156e+06  ...  {15D4B731-06EF-42FA-8981-8D2553281402}
3398 -8.885882e+06  ...  {319BFC78-5239-444B-A299-88F9EBCC7D11}
448  -8.884843e+06  ...  {4F052D38-822B-451F-8706-970F7692E84F}
1995 -8.885873e+06  ...  {2C7A8124-2161-4AA7-8F1D-2FEBFFD606D7}

[7 rows x 46 columns]